# Titanic Dataset Analysis using Pandas

### Part A: Dataset Exploration

 - Load the Titanic dataset into a DataFrame named `df`.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")

- Display:
   * First 5 rows
   * Last 5 rows
   * Dataset shape

In [3]:
df.head()

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [4]:
df.tail()

     survived  pclass  gender   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

In [5]:
df.shape

(891, 9)

- Display:
   * Column names
   * Data types of all columns (`Use df.dtypes`)

In [6]:
df.columns

Index(['survived', 'pclass', 'gender', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

- Display DataTypes

In [7]:
df.dtypes

survived      int64
pclass        int64
gender       object
age         float64
sibsp         int64
parch         int64
fare        float64
embarked     object
deck         object
dtype: object

- Summary statistics for all numerical columns

In [8]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### Part B: Filtering Data

- Display all passengers whose age is greater than 50.

In [9]:
print(df[df['age'] > 50])

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
6           0       1    male  54.0      0      0  51.8625        S    E
11          1       1  female  58.0      0      0  26.5500        S    C
15          1       2  female  55.0      0      0  16.0000        S  NaN
33          0       2    male  66.0      0      0  10.5000        S  NaN
54          0       1    male  65.0      0      1  61.9792        C    B
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
820         1       1  female  52.0      1      1  93.5000        S    B
829         1       1  female  62.0      0      0  80.0000      NaN    B
851         0       3    male  74.0      0      0   7.7750        S  NaN
857         1       1    male  51.0      0      0  26.5500        S    E
879         1       1  female  56.0      0      1  83.1583        C    C

[64 rows x 9 columns]

- Display all female passengers.

In [10]:
print(df[df['gender'] == 'female'])

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
8           1       3  female  27.0      0      2  11.1333        S  NaN
9           1       2  female  14.0      1      0  30.0708        C  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
880         1       2  female  25.0      0      1  26.0000        S  NaN
882         0       3  female  22.0      0      0  10.5167        S  NaN
885         0       3  female  39.0      0      5  29.1250        Q  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN

[314 rows x 9 columns]

- Display passengers who:
    * Survived

In [11]:
print(df.query('survived == 1'))

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
8           1       3  female  27.0      0      2  11.1333        S  NaN
9           1       2  female  14.0      1      0  30.0708        C  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
875         1       3  female  15.0      0      0   7.2250        C  NaN
879         1       1  female  56.0      0      1  83.1583        C    C
880         1       2  female  25.0      0      1  26.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
889         1       1    male  26.0      0      0  30.0000        C    C

[342 rows x 9 columns]

 * Were in First Class (`Pclass = 1`)

In [12]:
print(df.query('pclass == 1'))

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
1           1       1  female  38.0      1      0  71.2833        C    C
3           1       1  female  35.0      1      0  53.1000        S    C
6           0       1    male  54.0      0      0  51.8625        S    E
11          1       1  female  58.0      0      0  26.5500        S    C
23          1       1    male  28.0      0      0  35.5000        S    A
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
871         1       1  female  47.0      1      1  52.5542        S    D
872         0       1    male  33.0      0      0   5.0000        S    B
879         1       1  female  56.0      0      1  83.1583        C    C
887         1       1  female  19.0      0      0  30.0000        S    B
889         1       1    male  26.0      0      0  30.0000        C    C

[216 rows x 9 columns]

- Display passengers whose fare was greater than 100.

In [13]:
print(df.query('fare > 100').head())

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
27          0       1    male  19.0      3      2  263.0000        S    C
31          1       1  female   NaN      1      0  146.5208        C    B
88          1       1  female  23.0      3      2  263.0000        S    C
118         0       1    male  24.0      0      1  247.5208        C    B
195         1       1  female  58.0      0      0  146.5208        C    B

- Using `query()`, display passengers with:

   * Age > 30
   * Fare > 50

In [14]:
print(df.query('age > 30'))

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
1           1       1  female  38.0      1      0  71.2833        C    C
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
6           0       1    male  54.0      0      0  51.8625        S    E
11          1       1  female  58.0      0      0  26.5500        S    C
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
873         0       3    male  47.0      0      0   9.0000        S  NaN
879         1       1  female  56.0      0      1  83.1583        C    C
881         0       3    male  33.0      0      0   7.8958        S  NaN
885         0       3  female  39.0      0      5  29.1250        Q  NaN
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[305 rows x 9 columns]

In [15]:
print(df.query('fare > 50'))

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
1           1       1  female  38.0      1      0   71.2833        C    C
3           1       1  female  35.0      1      0   53.1000        S    C
6           0       1    male  54.0      0      0   51.8625        S    E
27          0       1    male  19.0      3      2  263.0000        S    C
31          1       1  female   NaN      1      0  146.5208        C    B
..        ...     ...     ...   ...    ...    ...       ...      ...  ...
856         1       1  female  45.0      1      1  164.8667        S  NaN
863         0       3  female   NaN      8      2   69.5500        S  NaN
867         0       1    male  31.0      0      0   50.4958        S    A
871         1       1  female  47.0      1      1   52.5542        S    D
879         1       1  female  56.0      0      1   83.1583        C    C

[160 rows x 9 columns]

- Display all passengers embarking from Southampton (`Embarked = 'S'`).

In [16]:
print(df[df['embarked'] == 'S'])

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
6           0       1    male  54.0      0      0  51.8625        S    E
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
883         0       2    male  28.0      0      0  10.5000        S  NaN
884         0       3    male  25.0      0      0   7.0500        S  NaN
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN

[644 rows x 9 columns]

### Part C: Unique Values and Counts

- Find all unique passenger classes.

In [17]:
print(df['pclass'].unique())

[3 1 2]

- Find the number of unique embarkation ports.

In [18]:
print(df['embarked'].unique())

['S' 'C' 'Q' nan]

- Display the number of passengers in each class.

In [19]:
print(df['pclass'].value_counts())

pclass
3    491
1    216
2    184
Name: count, dtype: int64

- Display the number of male and female passengers.

In [20]:
print(df['gender'].value_counts())

gender
male      577
female    314
Name: count, dtype: int64

- Display the number of survivors and non-survivors.

In [21]:
print(df['survived'].value_counts())

survived
0    549
1    342
Name: count, dtype: int64

### Part D: Sorting

- Display the 10 passengers who paid the highest fare.

In [22]:
print(df.sort_values('fare',ascending=False).head(10))

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
258         1       1  female  35.0      0      0  512.3292        C  NaN
737         1       1    male  35.0      0      0  512.3292        C    B
679         1       1    male  36.0      0      1  512.3292        C    B
88          1       1  female  23.0      3      2  263.0000        S    C
27          0       1    male  19.0      3      2  263.0000        S    C
341         1       1  female  24.0      3      2  263.0000        S    C
438         0       1    male  64.0      1      4  263.0000        S    C
311         1       1  female  18.0      2      2  262.3750        C    B
742         1       1  female  21.0      2      2  262.3750        C    B
118         0       1    male  24.0      0      1  247.5208        C    B

- Display the 10 youngest passengers.

In [23]:
print(df.sort_values('age').head(10))

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
803         1       3    male  0.42      0      1    8.5167        C  NaN
755         1       2    male  0.67      1      1   14.5000        S  NaN
644         1       3  female  0.75      2      1   19.2583        C  NaN
469         1       3  female  0.75      2      1   19.2583        C  NaN
78          1       2    male  0.83      0      2   29.0000        S  NaN
831         1       2    male  0.83      1      1   18.7500        S  NaN
305         1       1    male  0.92      1      2  151.5500        S    C
827         1       2    male  1.00      0      2   37.0042        C  NaN
381         1       3  female  1.00      0      2   15.7417        C  NaN
164         0       3    male  1.00      4      1   39.6875        S  NaN

- Sort the dataset by:

    * Passenger class
    * Age

In [24]:
print(df.sort_values(['pclass','age']).head())

     survived  pclass  gender    age  sibsp  parch      fare embarked deck
305         1       1    male   0.92      1      2  151.5500        S    C
297         0       1  female   2.00      1      2  151.5500        S    C
445         1       1    male   4.00      0      2   81.8583        S    A
802         1       1    male  11.00      1      2  120.0000        S    B
435         1       1  female  14.00      1      2  120.0000        S    B

### Part E: Missing Values

- Count missing values in each column.

In [25]:
print(df.isnull().sum())

survived      0
pclass        0
gender        0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

- Find how many missing ages exist.

In [26]:
print(df['age'].isnull().sum())

177

- Create a new DataFrame where missing ages are replaced with the mean age.

In [27]:
df_new = df.copy()
df_new['age'] = df['age'].fillna(df['age'].mean())
#print(df_new.isnull().sum())
print(df_new)

     survived  pclass  gender        age  sibsp  parch     fare embarked deck
0           0       3    male  22.000000      1      0   7.2500        S  NaN
1           1       1  female  38.000000      1      0  71.2833        C    C
2           1       3  female  26.000000      0      0   7.9250        S  NaN
3           1       1  female  35.000000      1      0  53.1000        S    C
4           0       3    male  35.000000      0      0   8.0500        S  NaN
..        ...     ...     ...        ...    ...    ...      ...      ...  ...
886         0       2    male  27.000000      0      0  13.0000        S  NaN
887         1       1  female  19.000000      0      0  30.0000        S    B
888         0       3  female  29.699118      1      2  23.4500        S  NaN
889         1       1    male  26.000000      0      0  30.0000        C    C
890         0       3    male  32.000000      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

- Create another DataFrame after removing all rows containing missing values.

In [28]:
df_clean = df.dropna()
#print(df_clean.isnull().sum())
print(df_clean)

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
1           1       1  female  38.0      1      0  71.2833        C    C
3           1       1  female  35.0      1      0  53.1000        S    C
6           0       1    male  54.0      0      0  51.8625        S    E
10          1       3  female   4.0      1      1  16.7000        S    G
11          1       1  female  58.0      0      0  26.5500        S    C
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
871         1       1  female  47.0      1      1  52.5542        S    D
872         0       1    male  33.0      0      0   5.0000        S    B
879         1       1  female  56.0      0      1  83.1583        C    C
887         1       1  female  19.0      0      0  30.0000        S    B
889         1       1    male  26.0      0      0  30.0000        C    C

[182 rows x 9 columns]

### Part F: Grouping

- Calculate the average age of passengers in each class.

In [29]:
print(df.groupby('pclass')['age'].mean())

pclass
1    38.233441
2    29.877630
3    25.140620
Name: age, dtype: float64

- Calculate the average fare paid in each class.

In [30]:
print(df.groupby('pclass')['fare'].mean())

pclass
1    84.154687
2    20.662183
3    13.675550
Name: fare, dtype: float64

- Find the survival rate by gender.

In [31]:
print(df.groupby('gender')['survived'].mean())

gender
female    0.742038
male      0.188908
Name: survived, dtype: float64

- Find the average age of males and females.

In [32]:
print(df.groupby('gender')['age'].mean())

gender
female    27.915709
male      30.726645
Name: age, dtype: float64

- Find the number of passengers embarking from each port.

In [33]:
print(df.groupby('embarked')['embarked'].count())

embarked
C    168
Q     77
S    644
Name: embarked, dtype: int64

### Part G: Mini Analysis Questions

- Which passenger class had the highest survival rate?
  * First class has the highest survival rate (`62%`)

In [34]:
print(df.groupby('pclass')['survived'].mean())

pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64

- Did females survive more often than males?
  * Yes , for Female Survival Rate is `74%`

In [35]:
print(df.groupby('gender')['survived'].mean())

gender
female    0.742038
male      0.188908
Name: survived, dtype: float64

- Which embarkation port had the most passengers?
  * `S` embarkation port had the most passengers

In [36]:
print(df['embarked'].value_counts().idxmax())

S

- What was the maximum fare paid?
  * Maximum Fare `512`

In [37]:
print(df['fare'].max())

512.3292

- What was the average age of passengers?
  * Average age is `29year`

In [38]:
print(df['age'].mean())

29.69911764705882